import ThemeSwitch from "@/components/theme-switch";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { ThemeToggle } from "@/components/theme-toogle";
import { ModeToggle } from "@/components/mode-toogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <head />

      <body className={inter.className}>
        <Providers attribute="class" defaultTheme="system" enableSystem>
          <ThemeToggle />
          <ModeToggle />
          <ThemeSwitch />
          {children}
          {/* ThemeSwitch só funcionava abaixo do children, agora funciona acima */}
        </Providers>
      </body>
    </html>
  );
}
